const mongoose = require('mongoose');

const missionSchema = new mongoose.Schema({
  apartment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Apartment',
    required: true,
  },
  assignedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  title: {
    type: String,
    required: true,
    trim: true,
  },
  description: {
    type: String,
    trim: true,
  },
  dateDebut: {
    type: Date,
    required: true,
  },
  dateFin: {
    type: Date,
    required: true,
  },
  status: {
    type: String,
    enum: ['En attente', 'En cours', 'Terminé', 'Problème'],
    default: 'En attente',
  },
  priority: {
    type: String,
    enum: ['Faible', 'Normale', 'Élevée', 'Urgente'],
    default: 'Normale',
  },
  checklist: [{
    task: String,
    completed: {
      type: Boolean,
      default: false,
    },
    completedAt: Date,
  }],
  instructions: {
    type: String,
    trim: true,
  },
  photosAvant: [{
    type: String,
  }],
  photosApres: [{
    type: String,
  }],
  documents: [{
    filename: String,
    originalName: String,
    uploadedAt: {
      type: Date,
      default: Date.now,
    },
  }],
  notes: {
    type: String,
    trim: true,
  },
  timeStarted: Date,
  timeCompleted: Date,
  estimatedDuration: Number, // in minutes
  actualDuration: Number, // in minutes
  cleaningPrice: {
    type: Number,
    default: 0,
    min: 0,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
  metadata: {
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Booking',
    },
    bookingSource: String,
    guestName: String,
  },
});

missionSchema.pre('save', function (next) {
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model('Mission', missionSchema);