// Script pour créer l'index unique sur les missions automatiques
require('dotenv').config();
const mongoose = require('mongoose');

async function createMissionIndex() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log('🔧 Création de l\'index unique pour les missions automatiques...');

    const db = mongoose.connection.db;
    const collection = db.collection('missions');

    // Supprimer l'index s'il existe déjà (pour recréation)
    try {
      await collection.dropIndex('unique_auto_mission_per_apartment_day');
      console.log('  ↳ Index existant supprimé');
    } catch (error) {
      // Index n'existe pas, c'est normal
    }

    // Créer le nouvel index unique
    await collection.createIndex(
      { 
        apartment: 1, 
        dateDebut: 1,
        'metadata.autoGenerated': 1
      }, 
      { 
        unique: true,
        partialFilterExpression: { 'metadata.autoGenerated': true },
        name: 'unique_auto_mission_per_apartment_day'
      }
    );

    console.log('✅ Index unique créé avec succès');
    console.log('  ↳ Nom: unique_auto_mission_per_apartment_day');
    console.log('  ↳ Champs: { apartment: 1, dateDebut: 1, "metadata.autoGenerated": 1 }');
    console.log('  ↳ Filtre: metadata.autoGenerated = true');

    // Vérifier que l'index a été créé
    const indexes = await collection.listIndexes().toArray();
    const ourIndex = indexes.find(idx => idx.name === 'unique_auto_mission_per_apartment_day');
    
    if (ourIndex) {
      console.log('✅ Index vérifié et actif');
    } else {
      console.log('❌ Erreur: Index non trouvé après création');
    }

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('❌ Erreur lors de la création de l\'index:', error);
    process.exit(1);
  }
}

createMissionIndex();